[package]
name = "plonky2"
description = "Recursive SNARKs based on Plonk and FRI"
version = "0.1.0"
authors = ["Daniel Lubarov <daniel@mirprotocol.org>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mir-protocol/plonky2"
keywords = ["cryptography", "SNARK", "FRI"]
categories = ["cryptography"]
edition = "2018"
default-run = "bench_recursion"

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"
itertools = "0.10.0"
num = "0.3"
rand = "0.7.3"
rand_chacha = "0.2.2"
rayon = "1.5.1"
unroll = "0.1.5"
anyhow = "1.0.40"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
num_bigint = "0.2.3"

[profile.release]
opt-level = 3
#lto = "fat"
#codegen-units = 1
