[workspace]
members = ["evm", "field", "maybe_rayon", "plonky2", "starky", "util"]
resolver = "2"

[profile.release]
opt-level = 3
incremental = true
#lto = "fat"
#codegen-units = 1

[profile.bench]
opt-level = 3

[patch.crates-io]
eth_trie_utils = { git = "https://github.com/mir-protocol/eth_trie_utils.git", rev = "7c2c65aca2cc6d21384137836b98277589f6fcba" }
plonky2_evm = { path = "evm" }
plonky2_field = { path = "field" }
plonky2_maybe_rayon = { path = "maybe_rayon" }
plonky2 = { path = "plonky2" }
starky = { path = "starky" }
plonky2_util = { path = "util" }
